### ISSUE TITLE
Could not resolve to contig ID

### ISSUE THREAD

**Issue by Xieeeee** [satijalab/scChromHMM#1]
Hi, 
Thanks for providing this tool and the exciting CUT&TAG-pro. When I try to run the example, it will raises an error 'thread 'main' panicked at 'Could not resolve to contig ID', src/fragment.rs:32:23'. The issue is gone when running chr1 only (via --onlyone).  I thought it fails to convert chromosome name to id, but I am not sure how to handle that. 

The completed log message is ⬇️

 2021-10-13T16:29:51.946Z INFO  carina::file > Found File w/ tag "model" at "/home/scChromHMM/example1/model_2.txt"
 2021-10-13T16:29:51.947Z INFO  schrom::hmm  > Read HMM model paramers: Found  { #states: 2, #assays: 3 }
 2021-10-13T16:29:51.947Z INFO  carina::file > Found File w/ tag "common_cells" at "/home/scChromHMM/example1/cells.txt"
 2021-10-13T16:29:51.952Z INFO  schrom::hmm  > Found 7201 cells in common assay, first cell=E2L1:AAACGCTGTAACCAGG
 2021-10-13T16:29:51.955Z INFO  carina::file > Found File(s) w/ tag "anchors" at ["/home/scChromHMM/example1/k27ac.txt", "/home/scChromHMM/example1/k27me3.txt", "/home/scChromHMM/example1/k4me1.txt"]
 2021-10-13T16:29:51.983Z INFO  schrom::hmm  > Found 3 assays with [19, 22, 32] cells and [2465, 3706, 3699] anchors
 2021-10-13T16:29:51.984Z INFO  carina::file > Found File(s) w/ tag "fragments" at ["/home/scChromHMM/example1/h3k27ac_fragments.tsv.gz", "/home/scChromHMM/example1/h3k27me3_fragments.tsv.gz", "/home/scChromHMM/example1/h3k4me1_fragments.tsv.gz"]
 2021-10-13T16:29:52.008Z INFO  schrom::hmm  > Found total 22 chromosomes
 2021-10-13T16:29:52.008Z INFO  schrom::hmm  > Starting forward backward
thread 'main' panicked at 'Could not resolve to contig ID', src/fragment.rs:32:23

Thanks for any suggestions!

**Comment by Xieeeee** [comment]
Hi, 
Following up to see whether I can get some suggestions, thanks!

**Comment by k3yavi** [comment]
Hi @Xieeeee ,

Thanks for reaching out, your intuition is correct that it's failing to convert chromosome name to id, reason being, the tools is designed by default to work with all 22 chromosomes and when run with the test data it fails since test data has fragments from only chromosome 1. We added the flag `--onlyone` to inform the tool to perform segmentation on chromosome 1 only and that's why you don't see error when you run the tool with `--onlyone` flag. Hope it helps.

**Comment by Xieeeee** [comment]
Hi @k3yavi ,
Really appreciate your answer. I will try running on my toy data soon and will let you know how it goes.
Cheers
